name: moodmap
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.69.2
  shared_preferences: ^2.1.0
  intl: ^0.18.0
  url_launcher: ^6.1.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: nunito
      fonts:
        - asset: assets/nunito.ttf